
language: c

compiler: gcc

addons:
  postgresql: "9.3"

env:
  global:
    - secure: cDfB188ECmloGfScZQezqwiFef7l+gXgn2RiTOxINriy9wYS6RmZxuZBHGuR36u7QV3QEJtMdihyQ+XBN2eQPf5jULQXV15t7gArXEVPzzF8i+f8MTgVHugU3TqmPLQkY94wBBbpzvRD9xCAC/uNiQcLLwuD2SjPfTXkqgqqtd0=
    - PGVERSION="9.3"
    - JANSSON_VERSION="2.9"
    - CK_DEFAULT_TIMEOUT=20
    - DISPOSABLE_IRODS_VERSION="1.2"
    - RENCI_URL=ftp://ftp.renci.org
    - WTSI_NPG_GITHUB_URL=https://github.com/wtsi-npg
  matrix:
    - IRODS_VERSION=3.3.1 IRODS_RIP_DIR=/usr/local/irods
    - IRODS_VERSION=4.1.10 PG_PLUGIN_VERSION=1.10 PLATFORM=ubuntu12

before_install:
  - ./scripts/travis_before_install.sh

install:
  - ./scripts/travis_install.sh

script:
  - export PATH=$IRODS_RIP_DIR/iRODS/clients/icommands/bin:$PATH
  - ienv
  - ils
  - ./scripts/travis_script.sh

after_success:
  - make dist
  - export DIST_FILE=$(ls baton-*.tar.gz)
  - export SHA256_FILE=$DIST_FILE.sha256
  - shasum -a 256 $DIST_FILE > $SHA256_FILE

deploy:
  provider: releases
  api-key: $GH_OAUTH
  file:
    - $DIST_FILE
    - $SHA256_FILE
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
