
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq odbc-postgresql unixodbc-dev super
  - sudo apt-get install -qq python-sphinx
  - sudo apt-get install -qq libboost-filesystem-dev libboost-regex-dev libboost-thread-dev
  - wget ftp://ftp.renci.org/pub/irods/releases/4.0.3/irods-icat-4.0.3-64bit.deb
  - wget ftp://ftp.renci.org/pub/irods/releases/4.0.3/irods-database-plugin-postgres-1.3.deb
  - wget ftp://ftp.renci.org/pub/irods/releases/4.0.3/irods-runtime-4.0.3-64bit.deb
  - wget ftp://ftp.renci.org/pub/irods/releases/4.0.3/irods-dev-4.0.3-64bit.deb
  - sudo dpkg -i irods-icat-4.0.3-64bit.deb irods-database-plugin-postgres-1.3.deb
  - sudo dpkg -i irods-runtime-4.0.3-64bit.deb irods-dev-4.0.3-64bit.deb

install:
  - wget http://downloads.sourceforge.net/project/check/check/0.9.14/check-0.9.14.tar.gz -O /tmp/check-0.9.14.tar.gz
  - tar xfz /tmp/check-0.9.14.tar.gz -C /tmp
  - cd /tmp/check-0.9.14 ; autoreconf -fi ; ./configure ; make ; sudo make install
  - wget https://github.com/akheron/jansson/archive/v2.6.tar.gz -O /tmp/jansson-2.6.tar.gz
  - tar xfz /tmp/jansson-2.6.tar.gz -C /tmp
  - cd /tmp/jansson-2.6 ; autoreconf -fi ; ./configure ; make ; sudo make install
  - cd $TRAVIS_BUILD_DIR
  - sudo ldconfig
  - sudo pip install breathe

language: c

compiler: gcc

addons:
  postgresql: "9.3"

env:
  global:
    - secure: cDfB188ECmloGfScZQezqwiFef7l+gXgn2RiTOxINriy9wYS6RmZxuZBHGuR36u7QV3QEJtMdihyQ+XBN2eQPf5jULQXV15t7gArXEVPzzF8i+f8MTgVHugU3TqmPLQkY94wBBbpzvRD9xCAC/uNiQcLLwuD2SjPfTXkqgqqtd0=
    - CK_DEFAULT_TIMEOUT=10
    - LD_LIBRARY_PATH=/usr/lib/irods

before_script:
  - sudo -E -u postgres createuser -D -R -S irods
  - sudo -E -u postgres createdb -O irods ICAT
  - sudo -E -u postgres sh -c "echo \"ALTER USER irods WITH PASSWORD 'irods'\" | psql"
  - sudo /var/lib/irods/packaging/setup_irods.sh < .travis.setup_irods
  - sudo perl -p -i.bak -e 's/(default_hash_scheme\s+)SHA256/$1MD5/' /etc/irods/server.config
  - ls -l /etc/irods
  - sudo /etc/init.d/irods restart
  - mkdir $HOME/.irods
  - cp .travis.irodsenv $HOME/.irods/.irodsEnv
  - echo "irodsUserName=$USER" >> $HOME/.irods/.irodsEnv
  - cat $HOME/.irods/.irodsEnv
  - sudo -E su irods -c "iadmin mkuser $USER rodsadmin ; iadmin moduser $USER password testuser"
  - echo testuser | script -q -c "iinit" > /dev/null

script:
  - autoreconf -fi
  - ./configure
  - make distcheck

after_success:
  - make dist
  - export DIST_FILE=$(ls baton-*.tar.gz)

deploy:
  provider: releases
  api-key: $GH_OAUTH
  file: $DIST_FILE
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
