
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq odbc-postgresql unixodbc-dev python-sphinx

install:
  - sudo pip install breathe

language: c

compiler: gcc

addons:
  postgresql: "9.3"

env:
  global:
    - secure: XyvnFLHHu9ABC7R0k0QtDBEIvNz1UgwiB2aAbN+mbTuNH5Bjgb7RqA0iLmXjjAyvfKarQOgzmvJXnrZvT47+9glDtPNPl6EwVZneGKpPqqh/2ScypfEnBW3LJfg1Jh6e4D41SJuXbcj5hXaLjjyhsjtDV/2HN1BVH1LCicTe/jM=
    - PGVERSION="9.3"
    - CK_DEFAULT_TIMEOUT=10
    - IRODS_VAULT=/usr/local/var/lib/irods/Vault

before_script:
  - wget http://downloads.sourceforge.net/project/check/check/0.9.14/check-0.9.14.tar.gz -O /tmp/check-0.9.14.tar.gz
  - tar xfz /tmp/check-0.9.14.tar.gz -C /tmp
  - cd /tmp/check-0.9.14 ; autoreconf -fi ; ./configure ; make ; sudo make install
  - wget https://github.com/akheron/jansson/archive/v2.6.tar.gz -O /tmp/jansson-2.6.tar.gz
  - tar xfz /tmp/jansson-2.6.tar.gz -C /tmp
  - cd /tmp/jansson-2.6 ; autoreconf -fi ; ./configure ; make ; sudo make install
  - sudo ldconfig
  - cd $TRAVIS_BUILD_DIR
  - wget https://github.com/wtsi-npg/irods-legacy/releases/download/3.3.1-travis-bc85aa/irods.tar.gz -O /tmp/irods.tar.gz
  - tar xfz /tmp/irods.tar.gz
  - source $TRAVIS_BUILD_DIR/travis_linux_env.sh
  - export PATH=$PATH:$IRODS_HOME/clients/icommands/bin
  - sudo mkdir -p $IRODS_VAULT
  - sudo chown $USER:$USER $IRODS_VAULT
  - sudo -E -u postgres $TRAVIS_BUILD_DIR/setup_pgusers.sh
  - sudo -E -u postgres $TRAVIS_BUILD_DIR/irodscontrol psetup
  - $TRAVIS_BUILD_DIR/irodscontrol istart ; sleep 10
  - echo irods | script -q -c "iinit" > /dev/null
  - ienv
  - ils

script:
  - source ./scripts/set_irods_home.sh
  - autoreconf -fi
  - ./configure
  - make distcheck

after_script:
  - $TRAVIS_BUILD_DIR/irodscontrol istop

after_success:
  - make dist
  - export DIST_FILE=$(ls baton-*.tar.gz | tr -d '\012')

deploy:
  provider: releases
  api-key: $GH_OAUTH
  file: $DIST_FILE
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
